version: "3.9"
services:
  pipeline:
    image: pipeline_image
    tty: True
    volumes:
      - ./jb:/srv/jb
      - ./data:/srv/data
      - ./scripts:/srv/scripts
      - ./git_clone:/srv/git_clone
  service:
    image: service_image
    tty: True
    volumes:
      - ./jb:/srv/jb
      - ./data:/srv/data
      - ./scripts:/srv/scripts
      - ./service:/srv/service
    ports:
      - 80:80

